### ISSUE TITLE
Useless code?

### ISSUE THREAD

**Issue by matsumoto777** [Waqas-Hirose/Assignment1_Waqas#2]
Please check below.
If it is useless code, you should delete it.

1) ContentView.swift
2) Storyboardに使っていない画面が入っています？
3) UsersListViewControllert.swift ↓
```
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if(indexPath.row < usersList.count){
            
        }
        
    }
```

**Comment by Waqas-Hirose** [comment]
1- Removed ContentView.swift 
2- There is no extra ViewController 
3- Removed unnecessary code
