### ISSUE TITLE
About class UserInfo

### ISSUE THREAD

**Issue by matsumoto777** [Waqas-Hirose/Assignment1_Waqas#3]
```
class UserInfo  {
    
    var id: Int
    var name: String
    
    init(id: Int, name: String) {
           self.name = name
           self.id = id
       }
}
```

1) Does this class need to be mutable? If it isn't need, you should change to immutable.
mutableは意図せず変更されることがあるので、扱いに慎重さを必要とします。
(Because mutables can change unintentionally, they need to be handled carefully.)
2) You should correct the indentation.
インデントや行間が整理されたソースコードは皆をハッピーにします。
Source code with indentation and line spacing makes everyone happy.

**Comment by Waqas-Hirose** [comment]
1- I thought that we may need to extend this class in future. For now I have made it immutable and will see in future if needed. We can change or write its extension if needed in future.
2- Alright!  This is done.

**Comment by matsumoto777** [comment]
最初はimmutableで作り、必要があればmutableに変更する。
この手順が正しいと思います。
First make it with immutable, change to mutable if necessary.
I think this procedure is correct.
