### ISSUE TITLE
Indentation of SortTypes 

### ISSUE THREAD

**Issue by matsumoto777** [Waqas-Hirose/Assignment1_Waqas#6]
```
enum SortTypes :Int{
case sortById
case sortByName
}
```

インデントや行間が整理されたソースコードは皆をハッピーにします。
Source code with **proper** indentation and line spacing makes everyone happy.

↓ Right
```
enum SortTypes :Int{
    case sortById
    case sortByName
}
```

Indentation is automatically organized by XCode, right?

**Comment by matsumoto777** [comment]
Force Indent
Ctrl + i

**Comment by Waqas-Hirose** [comment]
Changes are made
